version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    
    
  node:
    build: .
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "sleep 10 && npx sequelize-cli db:migrate && npm run dev"
    environment:
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DATABASE=docker
      - DB_HOST=postgres  
      - DB_PORT=5432



