version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - docker_pg_data:/bitnami/postgresql
    
  node:
    build: .
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev 
    environment:
      - DB_NAME=docker
      - DB_USER=docker
      - DB_PASS=docker
      - DB_HOST=postgres  
      - DB_PORT=5432

volumes:
  docker_pg_data:
